### ISSUE TITLE
link error for ppl_llama_server

### ISSUE THREAD

**Issue by lyg95** [openppl-public/ppl.llm.serving#14]
## What are the problems?(screenshots or detailed error messages)

I have installed libnccl, but still get the error.

/usr/bin/ld: CMakeFiles/ppl_llama_server.dir/src/models/llama/llama_server.cc.o: in function `ResourceManager::~ResourceManager()':
llama_server.cc:(.text._ZN15ResourceManagerD2Ev[_ZN15ResourceManagerD5Ev]+0xa8): undefined reference to `ncclCommDestroy'
/usr/bin/ld: CMakeFiles/ppl_llama_server.dir/src/models/llama/llama_server.cc.o: in function `ResourceManager::Init(unsigned int, unsigned long, unsigned long, float, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)':
llama_server.cc:(.text._ZN15ResourceManager4InitEjmmfRKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEE[_ZN15ResourceManager4InitEjmmfRKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEE]+0x13e): undefined reference to `ncclCommInitAll'
collect2: error: ld returned 1 exit status
make[2]: *** [CMakeFiles/ppl_llama_server.dir/build.make:195: ppl_llama_server] Error 1
make[1]: *** [CMakeFiles/Makefile2:1738: CMakeFiles/ppl_llama_server.dir/all] Error 2
make: *** [Makefile:156: all] Error 2

## What are the types of GPU/CPU you are using?
GPU  

## What's the operating system ppl.llm.serving runs on?
Ubuntu20.04

## What's the compiler and its version?

gcc/g++ 9.4

## Which version(commit id or tag) of ppl.llm.serving is used?

master

## What are the commands used to build ppl.llm.serving?

./build.sh -DPPLNN_USE_LLM_CUDA=ON -DPPLNN_CUDA_ENABLE_NCCL=OFF -DPPLNN_ENABLE_CUDA_JIT=OFF -DPPLNN_CUDA_ARCHITECTURES="'80;'" -DPPLCOMMON_CUDA_ARCHITECTURES="'80'"

**Comment by ouonline** [comment]
> ## What are the commands used to build ppl.llm.serving?
> ./build.sh -DPPLNN_USE_LLM_CUDA=ON -DPPLNN_CUDA_ENABLE_NCCL=OFF -DPPLNN_ENABLE_CUDA_JIT=OFF -DPPLNN_CUDA_ARCHITECTURES="'80;'" -DPPLCOMMON_CUDA_ARCHITECTURES="'80'"

change `-DPPLNN_CUDA_ENABLE_NCCL=OFF` to `-DPPLNN_CUDA_ENABLE_NCCL=ON`
