### ISSUE TITLE
support for huggingface llama?

### ISSUE THREAD

**Issue by sleepwalker2017** [openppl-public/ppl.llm.serving#16]
We use vicuna in huggingface format. I notice only meta format is supported ? Is that true?

**Comment by Alcanderian** [comment]
The script for converting huggingface format to meta format will be released ASAP in https://github.com/openppl-public/ppl.pmx

**Comment by sleepwalker2017** [comment]
> The script for converting huggingface format to meta format will be released ASAP in https://github.com/openppl-public/ppl.pmx

thank you, got it.

**Comment by Vincent-syr** [comment]
Here is the exporting script for llama hugging face
https://github.com/openppl-public/ppl.pmx/tree/master/model_zoo/llama/huggingface
