### ISSUE TITLE
How to disable kv cache 8-bit quantization? 

### ISSUE THREAD

**Issue by sleepwalker2017** [openppl-public/ppl.llm.serving#19]
I try to disable this feature by setting ` --quantized_cache 0` when exporting model, but when loading model, it coredumps, 

I see this:

```
if (model_config_.cache_quant_bit != 8 && model_config_.cache_quant_group != 8) {
        LOG(ERROR) << "only support cache_quant_bit == 8 and cache_quant_group == 8";
        return RC_INVALID_VALUE;
    }
```

**Comment by Alcanderian** [comment]
We are foucsing on performance optimization currently, and the cuda kernels are only support 8-bit kv cache to avoid the management of multiple copies of code.
And fp16 kv cache will be supported when the kernels are turning into stable.
