### ISSUE TITLE
ppl llm dependency grpc checkout error

### ISSUE THREAD

**Issue by yongchaoding** [openppl-public/ppl.llm.serving#2]
Cloning into '/workspace/dev/inference/ppl.llm.serving/deps/grpc/third_party/xds'...
Cloning into '/workspace/dev/inference/ppl.llm.serving/deps/grpc/third_party/zlib'...
Submodule path 'third_party/abseil-cpp': checked out 'c2435f8342c2d0ed8101cb43adfd605fdc52dca2'
Submodule path 'third_party/benchmark': checked out '015d1a091af6937488242b70121858bce8fd40e9'
error: Server does not allow request for unadvertised object 60209eb1ccc34d5deefb002d1b7f37545204f7f2
fatal: Fetched in submodule path 'third_party/bloaty', but it did not contain 60209eb1ccc34d5deefb002d1b7f37545204f7f2. Direct fetching of that commit failed.
fatal:
CMake Error at grpc-subbuild/grpc-populate-prefix/tmp/grpc-populate-gitclone.cmake:62 (message):
  Failed to update submodules in:
  '/workspace/dev/inference/ppl.llm.serving/deps/grpc'

gmake[2]: *** [CMakeFiles/grpc-populate.dir/build.make:102: grpc-populate-prefix/src/grpc-populate-stamp/grpc-populate-download] Error 1
gmake[1]: *** [CMakeFiles/Makefile2:83: CMakeFiles/grpc-populate.dir/all] Error 2
gmake: *** [Makefile:91: all] Error 2

**Comment by ouonline** [comment]
What's the build commands?

**Comment by yongchaoding** [comment]
./build.sh -DPPLNN_USE_LLM_CUDA=ON -DPPLNN_CUDA_ENABLE_NCCL=OFF -DPPLNN_ENABLE_CUDA_JIT=OFF -DPPLNN_CUDA_ARCHITECTURES="'80'" -DPPLCOMMON_CUDA_ARCHITECTURES="'80'"

**Comment by ouonline** [comment]
> ./build.sh -DPPLNN_USE_LLM_CUDA=ON -DPPLNN_CUDA_ENABLE_NCCL=OFF -DPPLNN_ENABLE_CUDA_JIT=OFF -DPPLNN_CUDA_ARCHITECTURES="'80'" -DPPLCOMMON_CUDA_ARCHITECTURES="'80'"

may be a network problem. you may try again or use a proxy.

**Comment by LMX-xin** [comment]
I also encountered this problem, and when I git clone grpc alone, no error is reported. The platform I use is linux and A800.

**Comment by Vincent-syr** [comment]
> I also encountered this problem, and when I git clone grpc alone, no error is reported. The platform I use is linux and A800.

Please check your git version. We require git version >= 2.7.0, and we use 2.41,0 in our environment.
