### ISSUE TITLE
How to control the request rate in this framework?

### ISSUE THREAD

**Issue by LRY89757** [openppl-public/ppl.llm.serving#20]
Thank you for great job! 
I just use your serving framework, but with some questions below:

how to control the request rate? I noticed that you just push all the batchrequest into the vector and send it to the server continuously, but I just want to fix the numbers of the request per second.

example like the vllm: https://github.com/vllm-project/vllm/blob/90eb3f43ca5228647c834243d98881d53c7745d0/benchmarks/benchmark_serving.py#L224

**Comment by LRY89757** [comment]
@ouonline @Alcanderian @Vincent-syr You're welcome to answer this question in your free time : )

**Comment by Vincent-syr** [comment]
The purpose of QPS benchmark is measure the server to in exterme circumstance, so we don't set sending interval (your mentioned request rate). If necessary, You could custumly add sleeping time as sending interval here: https://github.com/openppl-public/ppl.llm.serving/blob/master/tools/client_qps_measure.cc#L84

**Comment by LRY89757** [comment]
> The purpose of QPS benchmark is measure the server to in exterme circumstance, so we don't set sending interval (your mentioned request rate). If necessary, You could custumly add sleeping time as sending interval here: https://github.com/openppl-public/ppl.llm.serving/blob/master/tools/client_qps_measure.cc#L84

Many thanks to you!
