### ISSUE TITLE
error: 服务器不允许请求未公开的对象 60209eb1ccc34d5deefb002d1b7f37545204f7f2 获取了子模组路径 'third_party/bloaty'，但是它没有包含 60209eb1ccc34d5deefb002d1b7f37545204f7f2。直接获取该提交失败。

### ISSUE THREAD

**Issue by williamZQ** [openppl-public/ppl.llm.serving#27]
![image](https://github.com/openppl-public/ppl.llm.serving/assets/63858679/904b84cb-b020-48d9-b084-0bb6633a358f)

**Comment by Vincent-syr** [comment]
Please follow issue template.  It looks like git network or git version problem. We require git version >= 2.7.0
