### ISSUE TITLE
Compilation error

### ISSUE THREAD

**Issue by Liu-xiandong** [openppl-public/ppl.llm.serving#61]
## What are the problems?(screenshots or detailed error messages)

In file included from /home/liuxiandong/workspace/ppl/ppl.llm.serving/src/models/llama/llama_worker.h:25:0,
                 from /home/liuxiandong/workspace/ppl/ppl.llm.serving/src/models/llama/llama_worker.cc:18:
/home/liuxiandong/workspace/ppl/ppl.llm.serving/src/models/llama/../../utils/mpsc_request_scheduler.h:21:10: fatal error: ppl/common/event_count.h: No such file or directory
 #include "ppl/common/event_count.h"
          ^~~~~~~~~~~~~~~~~~~~~~~~~~
In file included from /home/liuxiandong/workspace/ppl/ppl.llm.serving/src/models/llama/llama_worker.h:25:0,
                 from /home/liuxiandong/workspace/ppl/ppl.llm.serving/src/models/factory.cc:19:
/home/liuxiandong/workspace/ppl/ppl.llm.serving/src/models/llama/../../utils/mpsc_request_scheduler.h:21:10: fatal error: ppl/common/event_count.h: No such file or directory
 #include "ppl/common/event_count.h"
          ^~~~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
compilation terminated.
CMakeFiles/ppl_llm_static.dir/build.make:75: recipe for target 'CMakeFiles/ppl_llm_static.dir/src/models/factory.cc.o' failed

## What are the types of GPU/CPU you are using?
GPU

**Comment by syheliel** [comment]
+1, I'm encountering the same error

**Comment by ouonline** [comment]
This is resolved by https://github.com/openppl-public/ppl.nn/commit/0c19aae0fecf679a0adb2d8c4bb1ea8f50558f7e. please `rm -rf deps/pplnn*` and try again.

**Comment by Liu-xiandong** [comment]
> This is resolved by [openppl-public/ppl.nn@0c19aae](https://github.com/openppl-public/ppl.nn/commit/0c19aae0fecf679a0adb2d8c4bb1ea8f50558f7e). please `rm -rf deps/pplnn*` and try again.

OK，Thank you
